# Chapter 2 from 0 to 0.01
## deal with vector

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,2]) # row vector(but actually it isn't)
b = np.array([[3],[5],[4]]) # col vector

In [4]:
print(a.shape, b.shape)

(5,) (3, 1)


In [6]:
a = a.T
b = b.T # transpose
print(a.shape, b.shape)

(5,) (1, 3)


In [7]:
a # because python doesn't care about direction of 1D array. It's not row or col vector.

array([1, 2, 3, 4, 2])

In [9]:
a  = np.array([[1,2,3,4,2]])
a.shape # using [[]] reture 2 dimension - row vector.

(1, 5)

In [10]:
a = a.T
a.shape # then it can be transposed.

(5, 1)

In [11]:
a.sum() # the book shows codes that np.sum(a) or sum(a), it is not OOP. "a" is already numpy object.

12

In [12]:
a.mean()

2.4

In [24]:
a = np.random.rand(int(1e6)) # 1e6 reture 100000.0 float value which is not appropriate for random function.
print(np.shape(a), len(a)) # here a is not array but tuple, so a.shape() is not callable. 
# rebember this for dealing withtensor tuple. use function type or len.

(1000000,) 1000000


In [18]:
a.sum()

499593.6285213744

In [26]:
c = np.array([1,2,3]) ; d = sum(c) ; e = d * np.mean(c) # use semicolon for multiple code in single line

In [27]:
print(e)

12.0


## deal with matrix

In [33]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(np.shape(a)) # a is tuple.
print(np.size(a))

(3, 3)
9


In [34]:
a[2,:] # call 3rd row, index start with 0

array([7, 8, 9])

In [38]:
a[2,1] = 55 # replace (3,2) element with 55 (instead of 8)

In [39]:
a[:2, 1:] # call 1st, 2nd row(except index 2), 2nd, 3rd col(include index 1)

array([[2, 3],
       [5, 6]])

In [41]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, 55,  9]])

In [42]:
a.T # .T work with matrix obviously.

array([[ 1,  4,  7],
       [ 2,  5, 55],
       [ 3,  6,  9]])